### ISSUE TITLE
Few-shot settings

### ISSUE THREAD

**Issue by AriesWYu** [ZhixiangSu/KRST#3]
Very good work, but I have a small question about the path filter in few-shot datasets.  Could you provide related datasets? `(entity_path_train.txt relation_path_train.txt ... et al )` The link in README is missing. Thanks for much!

**Comment by ZhixiangSu** [comment]
Our few-shot training dataset are files "train_1000.txt" and "train_2000.txt" provided in each data folder. While the validating and testing dataset remains the same as the full dataset. 

Please refer to the "Quick Start" section as follows:

**suffix: This is for few-shot settings, including _full, _2000, and _1000.**

Then execute the following command:

./generate_train_and_test.sh

After that you can see the paths relation prediction results.

**Comment by AriesWYu** [comment]
Thanks
